### ISSUE TITLE
Texture Window fails

### ISSUE THREAD

**Issue by kootstra-rene** [kootstra-rene/enge-js#20]
Some game that use texture windows do not render correctly. FFVII being the obvious example.
Propose to go to WebGL2 as texture windowing is hard to do in WebGL1

**Comment by zaykho** [comment]
> Propose to go to WebGL2 as texture windowing is hard to do in WebGL1

[Wouldn't this prevent a lot of devices/browser to work with the emulator ?](https://caniuse.com/webgl2)

Maybe an option to switch from Webgl1 & 2 would be a solution (at least, until the support is better) ?

**Comment by kootstra-rene** [comment]
https://caniuse.com/webgl2 says it is not a problem

**Comment by zaykho** [comment]
Yeah, but it's less than the webgl1 https://caniuse.com/webgl, which mean that some users on weird setup/devices would be locked out, which could be the audience for such emulator in the first place (easy to use everywhere).

Though,  I can understand that it's less of an importance than fixing stuff with webgl2.0, that's why I wonder if we could get a "toggle" between different solution (like we have on other emulator, like opengl/vulkan etc..).

**Comment by kootstra-rene** [comment]
I will leave the WebGL code intact and a toggle should be possible to make.

**Comment by kootstra-rene** [comment]
Completely fixed in WebGL2 and decided not to implement this in WebGL1. The WebGL1 renderer has too much issues and I do not have the time to fix it there.

**Comment by kootstra-rene** [comment]
closing issue, after updating readme with link to webgl2 version
