### ISSUE TITLE
No sound on Firefox

### ISSUE THREAD

**Issue by zaykho** [kootstra-rene/enge-js#3]
As the readme said: **"you'll need chrome for running this emulator"**, still, I wanted to test the emulator in FF (actually waterfox) and see what the difference are.

Turns out that, the emulator work fine in FF (graphics, stability and speed wise), the only thing that is missing is the sound.

Would be interesting to investigate what broke it in FF.

**Comment by kootstra-rene** [comment]
Did investigation recently. Likely found the cause and wrote a small program to test. It works on Firefox, Chrome, Safari and Edge. Need some time to adapt the code flow to fix it in the emulator.

**Comment by zaykho** [comment]
Nice work !

**Comment by kootstra-rene** [comment]
Well the example worked but can't get it to work with the emulator because the example does not update the sound buffer and the emulator does. After a lot more googling I found the following thread:
https://stackoverflow.com/questions/61567545/web-audio-api-updating-looping-buffer-data-in-real-time-impossible-in-firefox
Here they state that you should the AudioWorklet. That for me at this time is a big nono and in combination with the performance issue with FF and the fact that FF browser usage is only declining over time I have decided to drop FF support altogether. It is not worth the fuzz to support this browser. 

The only supported browsers will be safari and chromium based browsers which should be good for more than 80% of the browser users.

**Comment by user451421541757324** [comment]
Any chance of supporting Firefox now? @kootstra-rene

**Comment by kootstra-rene** [comment]
Well... no. Even though I now fully understand how the audio worklet works after developing a mod-player. Firefox stil has some other issues that prevent the emulator from running properly. In the mean time the browser share of firefox dropped from 3.91% in dec 2021 to 2.76% in mar 2024. So I stand by my previous remark: It is not worth the effort to support firefox.

**Comment by user451421541757324** [comment]
Got it, thanks anyway.
